server:
  port: 8088
spring:
  profiles:
    active: dev
  security:
    jwt:
      key: jwt-key
      # jwt 的有效时间（天）
      expire: 7
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 替换：【服务器公网IP】、【你的MySQL密码】
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 19501215
  data:
    redis:
      # redis 端口（默认6379，不用改）
      port: 6379
      # 替换：【服务器公网IP】
      host: localhost
      # 替换：【你的Redis密码】
      password: 123456
      # redis连接超时时间（毫秒）
      timeout: 10000
      # 数据库索引，默认为0
      database: 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    # 替换：【服务器公网IP】
    host: localhost
    # rabbitmq 端口（默认5672，不用改）
    port: 5672
    # 默认用户名是guest（如果没改的话，直接填guest）
    username: guest
    # 替换：【你修改后的RabbitMQ密码】
    password: 123456
    listener:
      simple:
        retry:
          enabled: true #是否开启消费者重试
          max-attempts: 3 #最大重试次数
          initial-interval: 6000 #重试间隔时间（单位毫秒）
          multiplier: 2 #间隔时间乘子，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间
          max-interval: 10000 #重试最大时间间隔（单位毫秒）
    # 邮箱队列名称（默认值，不用改）
    queue:
      email: email_queue
      log-login: log_login_queue
      log-system: log_system_queue
    # 邮箱交换机名称（默认值，不用改）
    exchange:
      email: email_exchange
      log: log_exchange
    # 邮箱路由键（默认值，不用改）
    routingKey:
      email: email_routing_key
      log-login: log_routing_key_login
      log-system: log_routing_key_system
  mail:
    # QQ邮箱SMTP服务器（不用改）
    host: smtp.qq.com
    # 替换：【你的QQ邮箱账号】
    username: 2417424266@qq.com
    # 替换：【你的QQ邮箱SMTP授权码】
    password: txjafsqmmygbecgi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  quartz:
#    # 将 Quartz 持久化方式修改为 jdbc
#    job-store-type: jdbc
#    properties:
#      org:
#        quartz:
#          scheduler:
#            # 实例节点 ID 自动生成
#            instanceId: AUTO
#          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            dataSource: quartz_jobs
#          dataSource:
#            quartz_jobs:
#              driver: com.mysql.cj.jdbc.Driver
#              # 关键修改：大写URL改为小写url
#              URL: jdbc:mysql://110.42.101.78:3306/blog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#              user: root
#              password: 123456
mail:
  link:
    apply:
      # 邮箱审核友链回调地址（如果不开启）apply-notice 则无需在意该配置，随便填写即可
      redirect-uri: https://43.139.71.86/link/email/apply
  # 是否开启文章邮箱评论提醒
  article-email-notice: true
  # 是否开启文章邮箱回复提醒
  article-reply-notice: false
  # 是否开启留言邮箱评论提醒
  message-email-notice: false
  # 是否开启新的留言提醒
  message-new-notice: true
  # 是否开启留言回复提醒
  message-reply-notice: true
  # 是否开启友链申请提醒（可以在邮箱中通过友链）
  apply-notice: true
  # 是否开启友链审核通知提醒对方
  pass-notice: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除
      logic-delete-field: isDeleted
      # 逻辑删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
      # id 自增
      id-type: auto

# springdoc-openapi项目配置，访问 http://127.0.0.1:8088/doc.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: xyz.kuailemao

oauth:
  # Gitee登录
  gitee:
    client-id: ade7d1e76e3ca847ffb4b3f14dab3dc565ddbca7017d39d1d8f4223252a30ad2
    client-secret: 75f05f73900369be8cc825c609d721f7fb2b0c8156914eabf82bb4d6d654c911
    redirect-uri: http://43.139.71.86:8088/oauth/gitee/callback
  # Github登录
  github:
    client-id: Ov23liyQJQPFUVzg7Fbk
    client-secret: db0711d1f0550b571616e1025743cf8f2f7880d3
    redirect-uri: http://43.139.71.86:8088/oauth/github/callback

web:
  index:
    path: http://43.139.71.86/

# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn

http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000

# 连接 minio
minio:
  endpoint: http://43.139.71.86:9000
  accessKey: minioadmin
  secretKey: Admin@123456
  bucketName: blog






















